# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69655eba88690d6abfcfb7fe68063ea4983132f62694122be3df98b7e49b13e0d98455eef621bd40de543d5d5fc46c3d9a0c2939242ba8c50dea6d9762e5ed57

test:
  secret_key_base: bcacedb7b9c4b1a4618775f1304a83c90e68f11ee1388e49db9846dfd2cff51e4059427f7ce7979268af652ad9685204ddde80633cb47e21f543e2114a703c7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
